on: [push, workflow_dispatch]

permissions:
    id-token: write

env:
    AZURE_RG_NAME: ${{ vars.PROJECT_NAME }}-rg-${{ vars.AZURE_RESOURCE_IDENTIFIER }}

jobs:
    deploy_infrastructure:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subcription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                enable-AzPSSession: true

            - name: Create respource group if not exists
              run: |
                az group show --name ${{ env.AZURE_RG_NAME }} || az groupe create -- name ${{ env.AZURE_RG_NAME }} --location ${{ secrets.AZURE_REGION }}

            - name: Deploy Bicep
              id: bicep_deploy
              uses: azure/arm-deploy@v2
              with:
                subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
                region: ${{ secrets.AZURE_REGION }}
                template: ./infrastructure/main.bicep
                parameters: project=${{ vars.PROJECT_NAME }} location=${{ secrets.AZURE_REGION }} identifier=${{ vars.AZURZ_RESOURCE_IDENTIFIER }}
                resourceGroupeName: ${{ env.AZURE_RG_NAME }}
