on: [push, workflow_dispatch]

permissions:
    id-token: write

env:
    AZURE_RG_NAME: ${{ vars.PROJECT_NAME }}-rg-${{ vars.AZURE_RESOURCE_IDENTIFIER }}

jobs:
    deploy_infrastructure:
        runs-on: ubuntu-latest
        environment: production

        outputs:
          appServiceName: ${{ steps.bicep_deploy.outputs.appServiceName }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                enable-AzPSSession: true

            - name: Create respource group if not exists
              run: |
                az group show --name ${{ env.AZURE_RG_NAME }} || az group create -- name ${{ env.AZURE_RG_NAME }} --location ${{ secrets.AZURE_REGION }}

            - name: Deploy Bicep
              id: bicep_deploy
              uses: azure/arm-deploy@v2
              with:
                subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
                region: ${{ secrets.AZURE_REGION }}
                template: ./infrastructure/main.bicep
                parameters: project=${{ vars.PROJECT_NAME }} location=${{ secrets.AZURE_REGION }} identifier=${{ vars.AZURE_RESOURCE_IDENTIFIER }}
                resourceGroupName: ${{ env.AZURE_RG_NAME }}

    deploy_backend:
      runs-on: ubuntu-latest
      needs: deploy_infrastructure
      environment: production

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Publish the app
        run: dotnet publish -c Release --property:PublishDir=publish
        working-directory: ./backend

      - name: Login to Azure 
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Deploy backend to App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ needs.deploy_infrastructure.outputs.appServiceName }}
          package: ./backend/ParkNDeploy.Api/publish 